### ISSUE TITLE
DoFlicky broken when I closed the window instead of pressing restart button after uninstalling nvidia drivers

### ISSUE THREAD

**Issue by Nikki1993** [solus-project/doflicky#12]
Dell XPS 15, installed drivers back and forth via doflicky all the time no problem. Once, instead of pressing restart button straight after uninstall I closed to window manually and replied via telegram desktop and went to power off -> shutdown. 

Turned on laptop to be greeted with a blinking underscore. As it turned out my xorg.conf still contained Nvidia references even though all nvidia packages were gone. Manually deleting xorg.conf and installing xorg-driver-video-intel fixes the problem **however** modesetting driver that previously worked just simply doesn't. I can only get into desktop by installing xorg-driver-video-intel or nvidia-current. 

Running `linux-management-tool configure gpu` results in the creation of xorg.conf with Nvidia references even if driver is not installed.

**Comment by ikeydoherty** [comment]
Solved in LDM on IRC
