### ISSUE TITLE
.desktop file has wrong permissions

### ISSUE THREAD

**Issue by ghost** [solus-project/doflicky#3]
Not sure where I should report this, but the file "/usr/share/applications/doflicky.desktop" has "-rw-rw-r--" file permissions, unlike all others .desktop files with "-rw-r--r--" permissions in that directory.

```
-rw-r--r--   1 root root   383 Dez 16 09:56 budgie-panel.desktop
-rw-r--r--   1 root root   314 Dez 16 09:56 budgie-polkit.desktop
-rw-r--r--   1 root root   298 Dez 16 09:56 budgie-wm.desktop
-rw-rw-r--   1 root root   352 Okt 18 02:00 doflicky.desktop
```

**Comment by ikeydoherty** [comment]
Good find, 664 not 644

**Comment by ikeydoherty** [comment]
IDK what setuptools is doing but I fixed in solus pkg with this: https://dev.solus-project.com/R652:fa37066768e0f1406dd7653ab95994c94f8b0df5
