### ISSUE TITLE
Wrong detection in nvidia drivers

### ISSUE THREAD

**Issue by yaymalaga** [solus-project/doflicky#7]
I'm using a nvidia gt730 and doflicky tell me to install nvidia-304 package instead of nvidia-glx-driver. 

Nvidia's drivers page also tell me to install latest driver too: http://www.nvidia.es/download/driverResults.aspx/121200/en

**Comment by ikeydoherty** [comment]
Please make sure you're actually running the latest doflicky, also please run it from the CLI and provide the output:

`doflicky-ui`

**Comment by yaymalaga** [comment]
Yeah I forgot to mention that today I clean installed the new Solus release.

The output os doflicky-ui is just this:
DEBUG: NVIDIA Graphics Driver (main series) shadowed by existing NVIDIA Graphics Driver (340.xx series)

As doflicky wasn't properly detected the driver version, I installed nvidia-glx-driver-common, nvidia-glx-driver-current and nvidia-glx-driver-32bit. And before running doflicky-ui I unistalled these packages and rebooted the system.

**Comment by NikolaiMagnussen** [comment]
#9 fixes this issue
The problem was due to a missing method call in a comparison

**Comment by ikeydoherty** [comment]
I done fucked up </>

**Comment by ikeydoherty** [comment]
https://dev.solus-project.com/R652:74ffa097078b617990125e957671381fc268b4d9 :)

**Comment by ikeydoherty** [comment]
Many thanks to @NikolaiMagnussen for finding the derp and fixing it!
